/*
 * This file is generated by jOOQ.
*/
package com.example.codeusageanalyzer.jooq.tables.records;


import com.example.codeusageanalyzer.jooq.tables.JClass;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassRecord extends UpdatableRecordImpl<JClassRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -1007492818;

    /**
     * Setter for <code>PUBLIC.CLASS.CLASS_ID</code>.
     */
    public void setClassId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CLASS.CLASS_ID</code>.
     */
    public String getClassId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CLASS.CLASS_NAME</code>.
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CLASS.CLASS_NAME</code>.
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CLASS.MODULE_ID</code>.
     */
    public void setModuleId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CLASS.MODULE_ID</code>.
     */
    public String getModuleId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CLASS.SUPER_CLASS_NAME</code>.
     */
    public void setSuperClassName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CLASS.SUPER_CLASS_NAME</code>.
     */
    public String getSuperClassName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return JClass.CLASS.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JClass.CLASS.CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JClass.CLASS.MODULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JClass.CLASS.SUPER_CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSuperClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JClassRecord value1(String value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JClassRecord value2(String value) {
        setClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JClassRecord value3(String value) {
        setModuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JClassRecord value4(String value) {
        setSuperClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JClassRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JClassRecord
     */
    public JClassRecord() {
        super(JClass.CLASS);
    }

    /**
     * Create a detached, initialised JClassRecord
     */
    public JClassRecord(String classId, String className, String moduleId, String superClassName) {
        super(JClass.CLASS);

        set(0, classId);
        set(1, className);
        set(2, moduleId);
        set(3, superClassName);
    }
}
