/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;


import com.example.codeusageanalyzer.jooq.tables.JClass;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassRecord extends UpdatableRecordImpl<JClassRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CLASS.CLASS_ID</code>.
     */
    public void setClassId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CLASS.CLASS_ID</code>.
     */
    public String getClassId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CLASS.CLASS_NAME</code>.
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CLASS.CLASS_NAME</code>.
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CLASS.MODULE_ID</code>.
     */
    public void setModuleId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CLASS.MODULE_ID</code>.
     */
    public String getModuleId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CLASS.SUPER_CLASS_NAME</code>.
     */
    public void setSuperClassName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CLASS.SUPER_CLASS_NAME</code>.
     */
    public String getSuperClassName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JClass.CLASS.CLASS_ID;
    }

    @Override
    public Field<String> field2() {
        return JClass.CLASS.CLASS_NAME;
    }

    @Override
    public Field<String> field3() {
        return JClass.CLASS.MODULE_ID;
    }

    @Override
    public Field<String> field4() {
        return JClass.CLASS.SUPER_CLASS_NAME;
    }

    @Override
    public String component1() {
        return getClassId();
    }

    @Override
    public String component2() {
        return getClassName();
    }

    @Override
    public String component3() {
        return getModuleId();
    }

    @Override
    public String component4() {
        return getSuperClassName();
    }

    @Override
    public String value1() {
        return getClassId();
    }

    @Override
    public String value2() {
        return getClassName();
    }

    @Override
    public String value3() {
        return getModuleId();
    }

    @Override
    public String value4() {
        return getSuperClassName();
    }

    @Override
    public JClassRecord value1(String value) {
        setClassId(value);
        return this;
    }

    @Override
    public JClassRecord value2(String value) {
        setClassName(value);
        return this;
    }

    @Override
    public JClassRecord value3(String value) {
        setModuleId(value);
        return this;
    }

    @Override
    public JClassRecord value4(String value) {
        setSuperClassName(value);
        return this;
    }

    @Override
    public JClassRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JClassRecord
     */
    public JClassRecord() {
        super(JClass.CLASS);
    }

    /**
     * Create a detached, initialised JClassRecord
     */
    public JClassRecord(String classId, String className, String moduleId, String superClassName) {
        super(JClass.CLASS);

        setClassId(classId);
        setClassName(className);
        setModuleId(moduleId);
        setSuperClassName(superClassName);
    }
}
