/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;


import com.example.codeusageanalyzer.jooq.tables.JDependency;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDependencyRecord extends UpdatableRecordImpl<JDependencyRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEPENDENCY.DEPENDENCY_ID</code>.
     */
    public void setDependencyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEPENDENCY.DEPENDENCY_ID</code>.
     */
    public String getDependencyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DEPENDENCY.ARTIFACT_ID</code>.
     */
    public void setArtifactId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEPENDENCY.ARTIFACT_ID</code>.
     */
    public String getArtifactId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DEPENDENCY.GROUP_ID</code>.
     */
    public void setGroupId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEPENDENCY.GROUP_ID</code>.
     */
    public String getGroupId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DEPENDENCY.MODULE_ID</code>.
     */
    public void setModuleId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEPENDENCY.MODULE_ID</code>.
     */
    public String getModuleId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DEPENDENCY.VERSION</code>.
     */
    public void setVersion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEPENDENCY.VERSION</code>.
     */
    public String getVersion() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JDependency.DEPENDENCY.DEPENDENCY_ID;
    }

    @Override
    public Field<String> field2() {
        return JDependency.DEPENDENCY.ARTIFACT_ID;
    }

    @Override
    public Field<String> field3() {
        return JDependency.DEPENDENCY.GROUP_ID;
    }

    @Override
    public Field<String> field4() {
        return JDependency.DEPENDENCY.MODULE_ID;
    }

    @Override
    public Field<String> field5() {
        return JDependency.DEPENDENCY.VERSION;
    }

    @Override
    public String component1() {
        return getDependencyId();
    }

    @Override
    public String component2() {
        return getArtifactId();
    }

    @Override
    public String component3() {
        return getGroupId();
    }

    @Override
    public String component4() {
        return getModuleId();
    }

    @Override
    public String component5() {
        return getVersion();
    }

    @Override
    public String value1() {
        return getDependencyId();
    }

    @Override
    public String value2() {
        return getArtifactId();
    }

    @Override
    public String value3() {
        return getGroupId();
    }

    @Override
    public String value4() {
        return getModuleId();
    }

    @Override
    public String value5() {
        return getVersion();
    }

    @Override
    public JDependencyRecord value1(String value) {
        setDependencyId(value);
        return this;
    }

    @Override
    public JDependencyRecord value2(String value) {
        setArtifactId(value);
        return this;
    }

    @Override
    public JDependencyRecord value3(String value) {
        setGroupId(value);
        return this;
    }

    @Override
    public JDependencyRecord value4(String value) {
        setModuleId(value);
        return this;
    }

    @Override
    public JDependencyRecord value5(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public JDependencyRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDependencyRecord
     */
    public JDependencyRecord() {
        super(JDependency.DEPENDENCY);
    }

    /**
     * Create a detached, initialised JDependencyRecord
     */
    public JDependencyRecord(String dependencyId, String artifactId, String groupId, String moduleId, String version) {
        super(JDependency.DEPENDENCY);

        setDependencyId(dependencyId);
        setArtifactId(artifactId);
        setGroupId(groupId);
        setModuleId(moduleId);
        setVersion(version);
    }
}
