/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;


import com.example.codeusageanalyzer.jooq.tables.JInterface;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JInterfaceRecord extends UpdatableRecordImpl<JInterfaceRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>INTERFACE.INTERFACE_ID</code>.
     */
    public void setInterfaceId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>INTERFACE.INTERFACE_ID</code>.
     */
    public String getInterfaceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>INTERFACE.CLASS_ID</code>.
     */
    public void setClassId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>INTERFACE.CLASS_ID</code>.
     */
    public String getClassId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>INTERFACE.INTERFACE_NAME</code>.
     */
    public void setInterfaceName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>INTERFACE.INTERFACE_NAME</code>.
     */
    public String getInterfaceName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JInterface.INTERFACE.INTERFACE_ID;
    }

    @Override
    public Field<String> field2() {
        return JInterface.INTERFACE.CLASS_ID;
    }

    @Override
    public Field<String> field3() {
        return JInterface.INTERFACE.INTERFACE_NAME;
    }

    @Override
    public String component1() {
        return getInterfaceId();
    }

    @Override
    public String component2() {
        return getClassId();
    }

    @Override
    public String component3() {
        return getInterfaceName();
    }

    @Override
    public String value1() {
        return getInterfaceId();
    }

    @Override
    public String value2() {
        return getClassId();
    }

    @Override
    public String value3() {
        return getInterfaceName();
    }

    @Override
    public JInterfaceRecord value1(String value) {
        setInterfaceId(value);
        return this;
    }

    @Override
    public JInterfaceRecord value2(String value) {
        setClassId(value);
        return this;
    }

    @Override
    public JInterfaceRecord value3(String value) {
        setInterfaceName(value);
        return this;
    }

    @Override
    public JInterfaceRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JInterfaceRecord
     */
    public JInterfaceRecord() {
        super(JInterface.INTERFACE);
    }

    /**
     * Create a detached, initialised JInterfaceRecord
     */
    public JInterfaceRecord(String interfaceId, String classId, String interfaceName) {
        super(JInterface.INTERFACE);

        setInterfaceId(interfaceId);
        setClassId(classId);
        setInterfaceName(interfaceName);
    }
}
