/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;


import com.example.codeusageanalyzer.jooq.tables.JModule;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JModuleRecord extends UpdatableRecordImpl<JModuleRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MODULE.MODULE_ID</code>.
     */
    public void setModuleId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>MODULE.MODULE_ID</code>.
     */
    public String getModuleId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>MODULE.ARTIFACT_ID</code>.
     */
    public void setArtifactId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MODULE.ARTIFACT_ID</code>.
     */
    public String getArtifactId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MODULE.GROUP_ID</code>.
     */
    public void setGroupId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MODULE.GROUP_ID</code>.
     */
    public String getGroupId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MODULE.PATH</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MODULE.PATH</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MODULE.REPOSITORY_ID</code>.
     */
    public void setRepositoryId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MODULE.REPOSITORY_ID</code>.
     */
    public String getRepositoryId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MODULE.VERSION</code>.
     */
    public void setVersion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>MODULE.VERSION</code>.
     */
    public String getVersion() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JModule.MODULE.MODULE_ID;
    }

    @Override
    public Field<String> field2() {
        return JModule.MODULE.ARTIFACT_ID;
    }

    @Override
    public Field<String> field3() {
        return JModule.MODULE.GROUP_ID;
    }

    @Override
    public Field<String> field4() {
        return JModule.MODULE.PATH;
    }

    @Override
    public Field<String> field5() {
        return JModule.MODULE.REPOSITORY_ID;
    }

    @Override
    public Field<String> field6() {
        return JModule.MODULE.VERSION;
    }

    @Override
    public String component1() {
        return getModuleId();
    }

    @Override
    public String component2() {
        return getArtifactId();
    }

    @Override
    public String component3() {
        return getGroupId();
    }

    @Override
    public String component4() {
        return getPath();
    }

    @Override
    public String component5() {
        return getRepositoryId();
    }

    @Override
    public String component6() {
        return getVersion();
    }

    @Override
    public String value1() {
        return getModuleId();
    }

    @Override
    public String value2() {
        return getArtifactId();
    }

    @Override
    public String value3() {
        return getGroupId();
    }

    @Override
    public String value4() {
        return getPath();
    }

    @Override
    public String value5() {
        return getRepositoryId();
    }

    @Override
    public String value6() {
        return getVersion();
    }

    @Override
    public JModuleRecord value1(String value) {
        setModuleId(value);
        return this;
    }

    @Override
    public JModuleRecord value2(String value) {
        setArtifactId(value);
        return this;
    }

    @Override
    public JModuleRecord value3(String value) {
        setGroupId(value);
        return this;
    }

    @Override
    public JModuleRecord value4(String value) {
        setPath(value);
        return this;
    }

    @Override
    public JModuleRecord value5(String value) {
        setRepositoryId(value);
        return this;
    }

    @Override
    public JModuleRecord value6(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public JModuleRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JModuleRecord
     */
    public JModuleRecord() {
        super(JModule.MODULE);
    }

    /**
     * Create a detached, initialised JModuleRecord
     */
    public JModuleRecord(String moduleId, String artifactId, String groupId, String path, String repositoryId, String version) {
        super(JModule.MODULE);

        setModuleId(moduleId);
        setArtifactId(artifactId);
        setGroupId(groupId);
        setPath(path);
        setRepositoryId(repositoryId);
        setVersion(version);
    }
}
