/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;


import com.example.codeusageanalyzer.jooq.tables.JRepository;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRepositoryRecord extends UpdatableRecordImpl<JRepositoryRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>REPOSITORY.REPOSITORY_ID</code>.
     */
    public void setRepositoryId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>REPOSITORY.REPOSITORY_ID</code>.
     */
    public String getRepositoryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>REPOSITORY.URL</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>REPOSITORY.URL</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JRepository.REPOSITORY.REPOSITORY_ID;
    }

    @Override
    public Field<String> field2() {
        return JRepository.REPOSITORY.URL;
    }

    @Override
    public String component1() {
        return getRepositoryId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String value1() {
        return getRepositoryId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public JRepositoryRecord value1(String value) {
        setRepositoryId(value);
        return this;
    }

    @Override
    public JRepositoryRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public JRepositoryRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JRepositoryRecord
     */
    public JRepositoryRecord() {
        super(JRepository.REPOSITORY);
    }

    /**
     * Create a detached, initialised JRepositoryRecord
     */
    public JRepositoryRecord(String repositoryId, String url) {
        super(JRepository.REPOSITORY);

        setRepositoryId(repositoryId);
        setUrl(url);
    }
}
