/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCalleePojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String  calleeId;
    private String  descriptor;
    private Boolean invokeDynamic;
    private String  methodId;
    private String  methodName;
    private String  ownerName;

    public JCalleePojo() {}

    public JCalleePojo(JCalleePojo value) {
        this.calleeId = value.calleeId;
        this.descriptor = value.descriptor;
        this.invokeDynamic = value.invokeDynamic;
        this.methodId = value.methodId;
        this.methodName = value.methodName;
        this.ownerName = value.ownerName;
    }

    public JCalleePojo(
        String  calleeId,
        String  descriptor,
        Boolean invokeDynamic,
        String  methodId,
        String  methodName,
        String  ownerName
    ) {
        this.calleeId = calleeId;
        this.descriptor = descriptor;
        this.invokeDynamic = invokeDynamic;
        this.methodId = methodId;
        this.methodName = methodName;
        this.ownerName = ownerName;
    }

    /**
     * Getter for <code>CALLEE.CALLEE_ID</code>.
     */
    public String getCalleeId() {
        return this.calleeId;
    }

    /**
     * Setter for <code>CALLEE.CALLEE_ID</code>.
     */
    public void setCalleeId(String calleeId) {
        this.calleeId = calleeId;
    }

    /**
     * Getter for <code>CALLEE.DESCRIPTOR</code>.
     */
    public String getDescriptor() {
        return this.descriptor;
    }

    /**
     * Setter for <code>CALLEE.DESCRIPTOR</code>.
     */
    public void setDescriptor(String descriptor) {
        this.descriptor = descriptor;
    }

    /**
     * Getter for <code>CALLEE.INVOKE_DYNAMIC</code>.
     */
    public Boolean getInvokeDynamic() {
        return this.invokeDynamic;
    }

    /**
     * Setter for <code>CALLEE.INVOKE_DYNAMIC</code>.
     */
    public void setInvokeDynamic(Boolean invokeDynamic) {
        this.invokeDynamic = invokeDynamic;
    }

    /**
     * Getter for <code>CALLEE.METHOD_ID</code>.
     */
    public String getMethodId() {
        return this.methodId;
    }

    /**
     * Setter for <code>CALLEE.METHOD_ID</code>.
     */
    public void setMethodId(String methodId) {
        this.methodId = methodId;
    }

    /**
     * Getter for <code>CALLEE.METHOD_NAME</code>.
     */
    public String getMethodName() {
        return this.methodName;
    }

    /**
     * Setter for <code>CALLEE.METHOD_NAME</code>.
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * Getter for <code>CALLEE.OWNER_NAME</code>.
     */
    public String getOwnerName() {
        return this.ownerName;
    }

    /**
     * Setter for <code>CALLEE.OWNER_NAME</code>.
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JCalleePojo (");

        sb.append(calleeId);
        sb.append(", ").append(descriptor);
        sb.append(", ").append(invokeDynamic);
        sb.append(", ").append(methodId);
        sb.append(", ").append(methodName);
        sb.append(", ").append(ownerName);

        sb.append(")");
        return sb.toString();
    }
}
