/*
 * This file is generated by jOOQ.
*/
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassPojo implements Serializable {

    private static final long serialVersionUID = -1675605230;

    private String classId;
    private String className;
    private String moduleId;
    private String superClassName;

    public JClassPojo() {}

    public JClassPojo(JClassPojo value) {
        this.classId = value.classId;
        this.className = value.className;
        this.moduleId = value.moduleId;
        this.superClassName = value.superClassName;
    }

    public JClassPojo(
        String classId,
        String className,
        String moduleId,
        String superClassName
    ) {
        this.classId = classId;
        this.className = className;
        this.moduleId = moduleId;
        this.superClassName = superClassName;
    }

    public String getClassId() {
        return this.classId;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getModuleId() {
        return this.moduleId;
    }

    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    public String getSuperClassName() {
        return this.superClassName;
    }

    public void setSuperClassName(String superClassName) {
        this.superClassName = superClassName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JClassPojo (");

        sb.append(classId);
        sb.append(", ").append(className);
        sb.append(", ").append(moduleId);
        sb.append(", ").append(superClassName);

        sb.append(")");
        return sb.toString();
    }
}
