/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String classId;
    private String className;
    private String moduleId;
    private String superClassName;

    public JClassPojo() {}

    public JClassPojo(JClassPojo value) {
        this.classId = value.classId;
        this.className = value.className;
        this.moduleId = value.moduleId;
        this.superClassName = value.superClassName;
    }

    public JClassPojo(
        String classId,
        String className,
        String moduleId,
        String superClassName
    ) {
        this.classId = classId;
        this.className = className;
        this.moduleId = moduleId;
        this.superClassName = superClassName;
    }

    /**
     * Getter for <code>CLASS.CLASS_ID</code>.
     */
    public String getClassId() {
        return this.classId;
    }

    /**
     * Setter for <code>CLASS.CLASS_ID</code>.
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * Getter for <code>CLASS.CLASS_NAME</code>.
     */
    public String getClassName() {
        return this.className;
    }

    /**
     * Setter for <code>CLASS.CLASS_NAME</code>.
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * Getter for <code>CLASS.MODULE_ID</code>.
     */
    public String getModuleId() {
        return this.moduleId;
    }

    /**
     * Setter for <code>CLASS.MODULE_ID</code>.
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * Getter for <code>CLASS.SUPER_CLASS_NAME</code>.
     */
    public String getSuperClassName() {
        return this.superClassName;
    }

    /**
     * Setter for <code>CLASS.SUPER_CLASS_NAME</code>.
     */
    public void setSuperClassName(String superClassName) {
        this.superClassName = superClassName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JClassPojo (");

        sb.append(classId);
        sb.append(", ").append(className);
        sb.append(", ").append(moduleId);
        sb.append(", ").append(superClassName);

        sb.append(")");
        return sb.toString();
    }
}
