/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDependencyPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String dependencyId;
    private String artifactId;
    private String groupId;
    private String moduleId;
    private String version;

    public JDependencyPojo() {}

    public JDependencyPojo(JDependencyPojo value) {
        this.dependencyId = value.dependencyId;
        this.artifactId = value.artifactId;
        this.groupId = value.groupId;
        this.moduleId = value.moduleId;
        this.version = value.version;
    }

    public JDependencyPojo(
        String dependencyId,
        String artifactId,
        String groupId,
        String moduleId,
        String version
    ) {
        this.dependencyId = dependencyId;
        this.artifactId = artifactId;
        this.groupId = groupId;
        this.moduleId = moduleId;
        this.version = version;
    }

    /**
     * Getter for <code>DEPENDENCY.DEPENDENCY_ID</code>.
     */
    public String getDependencyId() {
        return this.dependencyId;
    }

    /**
     * Setter for <code>DEPENDENCY.DEPENDENCY_ID</code>.
     */
    public void setDependencyId(String dependencyId) {
        this.dependencyId = dependencyId;
    }

    /**
     * Getter for <code>DEPENDENCY.ARTIFACT_ID</code>.
     */
    public String getArtifactId() {
        return this.artifactId;
    }

    /**
     * Setter for <code>DEPENDENCY.ARTIFACT_ID</code>.
     */
    public void setArtifactId(String artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * Getter for <code>DEPENDENCY.GROUP_ID</code>.
     */
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Setter for <code>DEPENDENCY.GROUP_ID</code>.
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * Getter for <code>DEPENDENCY.MODULE_ID</code>.
     */
    public String getModuleId() {
        return this.moduleId;
    }

    /**
     * Setter for <code>DEPENDENCY.MODULE_ID</code>.
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * Getter for <code>DEPENDENCY.VERSION</code>.
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>DEPENDENCY.VERSION</code>.
     */
    public void setVersion(String version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JDependencyPojo (");

        sb.append(dependencyId);
        sb.append(", ").append(artifactId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(moduleId);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
