/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JInterfacePojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String interfaceId;
    private String classId;
    private String interfaceName;

    public JInterfacePojo() {}

    public JInterfacePojo(JInterfacePojo value) {
        this.interfaceId = value.interfaceId;
        this.classId = value.classId;
        this.interfaceName = value.interfaceName;
    }

    public JInterfacePojo(
        String interfaceId,
        String classId,
        String interfaceName
    ) {
        this.interfaceId = interfaceId;
        this.classId = classId;
        this.interfaceName = interfaceName;
    }

    /**
     * Getter for <code>INTERFACE.INTERFACE_ID</code>.
     */
    public String getInterfaceId() {
        return this.interfaceId;
    }

    /**
     * Setter for <code>INTERFACE.INTERFACE_ID</code>.
     */
    public void setInterfaceId(String interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * Getter for <code>INTERFACE.CLASS_ID</code>.
     */
    public String getClassId() {
        return this.classId;
    }

    /**
     * Setter for <code>INTERFACE.CLASS_ID</code>.
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * Getter for <code>INTERFACE.INTERFACE_NAME</code>.
     */
    public String getInterfaceName() {
        return this.interfaceName;
    }

    /**
     * Setter for <code>INTERFACE.INTERFACE_NAME</code>.
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JInterfacePojo (");

        sb.append(interfaceId);
        sb.append(", ").append(classId);
        sb.append(", ").append(interfaceName);

        sb.append(")");
        return sb.toString();
    }
}
