/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JMethodPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String methodId;
    private String classId;
    private String descriptor;
    private String methodName;

    public JMethodPojo() {}

    public JMethodPojo(JMethodPojo value) {
        this.methodId = value.methodId;
        this.classId = value.classId;
        this.descriptor = value.descriptor;
        this.methodName = value.methodName;
    }

    public JMethodPojo(
        String methodId,
        String classId,
        String descriptor,
        String methodName
    ) {
        this.methodId = methodId;
        this.classId = classId;
        this.descriptor = descriptor;
        this.methodName = methodName;
    }

    /**
     * Getter for <code>METHOD.METHOD_ID</code>.
     */
    public String getMethodId() {
        return this.methodId;
    }

    /**
     * Setter for <code>METHOD.METHOD_ID</code>.
     */
    public void setMethodId(String methodId) {
        this.methodId = methodId;
    }

    /**
     * Getter for <code>METHOD.CLASS_ID</code>.
     */
    public String getClassId() {
        return this.classId;
    }

    /**
     * Setter for <code>METHOD.CLASS_ID</code>.
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * Getter for <code>METHOD.DESCRIPTOR</code>.
     */
    public String getDescriptor() {
        return this.descriptor;
    }

    /**
     * Setter for <code>METHOD.DESCRIPTOR</code>.
     */
    public void setDescriptor(String descriptor) {
        this.descriptor = descriptor;
    }

    /**
     * Getter for <code>METHOD.METHOD_NAME</code>.
     */
    public String getMethodName() {
        return this.methodName;
    }

    /**
     * Setter for <code>METHOD.METHOD_NAME</code>.
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JMethodPojo (");

        sb.append(methodId);
        sb.append(", ").append(classId);
        sb.append(", ").append(descriptor);
        sb.append(", ").append(methodName);

        sb.append(")");
        return sb.toString();
    }
}
