/*
 * This file is generated by jOOQ.
*/
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JMethodPojo implements Serializable {

    private static final long serialVersionUID = -561969553;

    private String methodId;
    private String classId;
    private String descriptor;
    private String methodName;

    public JMethodPojo() {}

    public JMethodPojo(JMethodPojo value) {
        this.methodId = value.methodId;
        this.classId = value.classId;
        this.descriptor = value.descriptor;
        this.methodName = value.methodName;
    }

    public JMethodPojo(
        String methodId,
        String classId,
        String descriptor,
        String methodName
    ) {
        this.methodId = methodId;
        this.classId = classId;
        this.descriptor = descriptor;
        this.methodName = methodName;
    }

    public String getMethodId() {
        return this.methodId;
    }

    public void setMethodId(String methodId) {
        this.methodId = methodId;
    }

    public String getClassId() {
        return this.classId;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    public String getDescriptor() {
        return this.descriptor;
    }

    public void setDescriptor(String descriptor) {
        this.descriptor = descriptor;
    }

    public String getMethodName() {
        return this.methodName;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JMethodPojo (");

        sb.append(methodId);
        sb.append(", ").append(classId);
        sb.append(", ").append(descriptor);
        sb.append(", ").append(methodName);

        sb.append(")");
        return sb.toString();
    }
}
