/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRepositoryPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String repositoryId;
    private String url;

    public JRepositoryPojo() {}

    public JRepositoryPojo(JRepositoryPojo value) {
        this.repositoryId = value.repositoryId;
        this.url = value.url;
    }

    public JRepositoryPojo(
        String repositoryId,
        String url
    ) {
        this.repositoryId = repositoryId;
        this.url = url;
    }

    /**
     * Getter for <code>REPOSITORY.REPOSITORY_ID</code>.
     */
    public String getRepositoryId() {
        return this.repositoryId;
    }

    /**
     * Setter for <code>REPOSITORY.REPOSITORY_ID</code>.
     */
    public void setRepositoryId(String repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * Getter for <code>REPOSITORY.URL</code>.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>REPOSITORY.URL</code>.
     */
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JRepositoryPojo (");

        sb.append(repositoryId);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
