/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import com.example.codeusageanalyzer.jooq.JPublic;
import com.example.codeusageanalyzer.jooq.Keys;
import com.example.codeusageanalyzer.jooq.tables.records.JModuleRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JModule extends TableImpl<JModuleRecord> {

    private static final long serialVersionUID = -1013993962;

    /**
     * The reference instance of <code>PUBLIC.MODULE</code>
     */
    public static final JModule MODULE = new JModule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JModuleRecord> getRecordType() {
        return JModuleRecord.class;
    }

    /**
     * The column <code>PUBLIC.MODULE.MODULE_ID</code>.
     */
    public final TableField<JModuleRecord, Long> MODULE_ID = createField("MODULE_ID",
            org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.MODULE.ARTIFACT_ID</code>.
     */
    public final TableField<JModuleRecord, String> ARTIFACT_ID = createField("ARTIFACT_ID",
            org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.MODULE.GROUP_ID</code>.
     */
    public final TableField<JModuleRecord, String> GROUP_ID = createField("GROUP_ID",
            org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.MODULE.PATH</code>.
     */
    public final TableField<JModuleRecord, String> PATH = createField("PATH",
            org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.MODULE.REPOSITORY_ID</code>.
     */
    public final TableField<JModuleRecord, Long> REPOSITORY_ID = createField("REPOSITORY_ID",
            org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.MODULE.VERSION</code>.
     */
    public final TableField<JModuleRecord, String> VERSION = createField("VERSION",
            org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.MODULE</code> table reference
     */
    public JModule() {
        this("MODULE", null);
    }

    /**
     * Create an aliased <code>PUBLIC.MODULE</code> table reference
     */
    public JModule(String alias) {
        this(alias, MODULE);
    }

    private JModule(String alias, Table<JModuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private JModule(String alias, Table<JModuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JModuleRecord, Long> getIdentity() {
        return Keys.IDENTITY_MODULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JModuleRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_87;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JModuleRecord>> getKeys() {
        return Arrays.<UniqueKey<JModuleRecord>>asList(Keys.CONSTRAINT_87);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModule as(String alias) {
        return new JModule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JModule rename(String name) {
        return new JModule(name, null);
    }
}
