/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import com.example.codeusageanalyzer.jooq.JPublic;
import com.example.codeusageanalyzer.jooq.Keys;
import com.example.codeusageanalyzer.jooq.tables.records.JRepositoryRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRepository extends TableImpl<JRepositoryRecord> {

    private static final long serialVersionUID = -2141715430;

    /**
     * The reference instance of <code>PUBLIC.REPOSITORY</code>
     */
    public static final JRepository REPOSITORY = new JRepository();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JRepositoryRecord> getRecordType() {
        return JRepositoryRecord.class;
    }

    /**
     * The column <code>PUBLIC.REPOSITORY.REPOSITORY_ID</code>.
     */
    public final TableField<JRepositoryRecord, Long> REPOSITORY_ID = createField("REPOSITORY_ID",
            org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.REPOSITORY.URL</code>.
     */
    public final TableField<JRepositoryRecord, String> URL = createField("URL",
            org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.REPOSITORY</code> table reference
     */
    public JRepository() {
        this("REPOSITORY", null);
    }

    /**
     * Create an aliased <code>PUBLIC.REPOSITORY</code> table reference
     */
    public JRepository(String alias) {
        this(alias, REPOSITORY);
    }

    private JRepository(String alias, Table<JRepositoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private JRepository(String alias, Table<JRepositoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JRepositoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JRepositoryRecord>> getKeys() {
        return Arrays.<UniqueKey<JRepositoryRecord>>asList(Keys.CONSTRAINT_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JRepository as(String alias) {
        return new JRepository(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JRepository rename(String name) {
        return new JRepository(name, null);
    }
}
