/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import com.example.codeusageanalyzer.jooq.tables.JCallee;
import com.example.codeusageanalyzer.jooq.tables.JClass;
import com.example.codeusageanalyzer.jooq.tables.JDependency;
import com.example.codeusageanalyzer.jooq.tables.JInterface;
import com.example.codeusageanalyzer.jooq.tables.JMethod;
import com.example.codeusageanalyzer.jooq.tables.JModule;
import com.example.codeusageanalyzer.jooq.tables.JRepository;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPublic extends SchemaImpl {

    private static final long serialVersionUID = -31595858;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final JPublic PUBLIC = new JPublic();

    /**
     * The table <code>PUBLIC.CALLEE</code>.
     */
    public final JCallee CALLEE = com.example.codeusageanalyzer.jooq.tables.JCallee.CALLEE;

    /**
     * The table <code>PUBLIC.CLASS</code>.
     */
    public final JClass CLASS = com.example.codeusageanalyzer.jooq.tables.JClass.CLASS;

    /**
     * The table <code>PUBLIC.DEPENDENCY</code>.
     */
    public final JDependency DEPENDENCY = com.example.codeusageanalyzer.jooq.tables.JDependency.DEPENDENCY;

    /**
     * The table <code>PUBLIC.INTERFACE</code>.
     */
    public final JInterface INTERFACE = com.example.codeusageanalyzer.jooq.tables.JInterface.INTERFACE;

    /**
     * The table <code>PUBLIC.METHOD</code>.
     */
    public final JMethod METHOD = com.example.codeusageanalyzer.jooq.tables.JMethod.METHOD;

    /**
     * The table <code>PUBLIC.MODULE</code>.
     */
    public final JModule MODULE = com.example.codeusageanalyzer.jooq.tables.JModule.MODULE;

    /**
     * The table <code>PUBLIC.REPOSITORY</code>.
     */
    public final JRepository REPOSITORY = com.example.codeusageanalyzer.jooq.tables.JRepository.REPOSITORY;

    /**
     * No further instances allowed
     */
    private JPublic() {
        super("PUBLIC", null);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(JCallee.CALLEE, JClass.CLASS, JDependency.DEPENDENCY, JInterface.INTERFACE,
                JMethod.METHOD, JModule.MODULE, JRepository.REPOSITORY);
    }
}
