/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import com.example.codeusageanalyzer.jooq.tables.JCallee;
import com.example.codeusageanalyzer.jooq.tables.JClass;
import com.example.codeusageanalyzer.jooq.tables.JDependency;
import com.example.codeusageanalyzer.jooq.tables.JInterface;
import com.example.codeusageanalyzer.jooq.tables.JMethod;
import com.example.codeusageanalyzer.jooq.tables.JModule;
import com.example.codeusageanalyzer.jooq.tables.JRepository;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPublic extends SchemaImpl {

    private static final long serialVersionUID = -1147221871;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final JPublic PUBLIC = new JPublic();

    /**
     * The table <code>PUBLIC.CALLEE</code>.
     */
    public final JCallee CALLEE = com.example.codeusageanalyzer.jooq.tables.JCallee.CALLEE;

    /**
     * The table <code>PUBLIC.CLASS</code>.
     */
    public final JClass CLASS = com.example.codeusageanalyzer.jooq.tables.JClass.CLASS;

    /**
     * The table <code>PUBLIC.DEPENDENCY</code>.
     */
    public final JDependency DEPENDENCY = com.example.codeusageanalyzer.jooq.tables.JDependency.DEPENDENCY;

    /**
     * The table <code>PUBLIC.INTERFACE</code>.
     */
    public final JInterface INTERFACE = com.example.codeusageanalyzer.jooq.tables.JInterface.INTERFACE;

    /**
     * The table <code>PUBLIC.METHOD</code>.
     */
    public final JMethod METHOD = com.example.codeusageanalyzer.jooq.tables.JMethod.METHOD;

    /**
     * The table <code>PUBLIC.MODULE</code>.
     */
    public final JModule MODULE = com.example.codeusageanalyzer.jooq.tables.JModule.MODULE;

    /**
     * The table <code>PUBLIC.REPOSITORY</code>.
     */
    public final JRepository REPOSITORY = com.example.codeusageanalyzer.jooq.tables.JRepository.REPOSITORY;

    /**
     * No further instances allowed
     */
    private JPublic() {
        super("PUBLIC", null);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(Sequences.SYSTEM_SEQUENCE_329F1A32_FD9C_4A30_9AD8_B932786E96B3,
                Sequences.SYSTEM_SEQUENCE_7344AA6C_A669_4CF1_B5B1_1D444518C7FD,
                Sequences.SYSTEM_SEQUENCE_7E7C649D_E9A0_49A3_9F00_1C62CA820F2E,
                Sequences.SYSTEM_SEQUENCE_847C61D6_2411_425A_BE5F_7696CB151706,
                Sequences.SYSTEM_SEQUENCE_B1E2D4A2_0A0C_4447_AF80_82B9EF5D5FDC,
                Sequences.SYSTEM_SEQUENCE_CDD9F9E2_D1E4_49AD_B1A2_DB99C16DC788,
                Sequences.SYSTEM_SEQUENCE_ED82774E_9477_4D87_9219_588259F46C85);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(JCallee.CALLEE, JClass.CLASS, JDependency.DEPENDENCY, JInterface.INTERFACE,
                JMethod.METHOD, JModule.MODULE, JRepository.REPOSITORY);
    }
}
