/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import com.example.codeusageanalyzer.jooq.tables.JCallee;
import com.example.codeusageanalyzer.jooq.tables.JClass;
import com.example.codeusageanalyzer.jooq.tables.JDependency;
import com.example.codeusageanalyzer.jooq.tables.JInterface;
import com.example.codeusageanalyzer.jooq.tables.JMethod;
import com.example.codeusageanalyzer.jooq.tables.JModule;
import com.example.codeusageanalyzer.jooq.tables.JRepository;
import com.example.codeusageanalyzer.jooq.tables.records.JCalleeRecord;
import com.example.codeusageanalyzer.jooq.tables.records.JClassRecord;
import com.example.codeusageanalyzer.jooq.tables.records.JDependencyRecord;
import com.example.codeusageanalyzer.jooq.tables.records.JInterfaceRecord;
import com.example.codeusageanalyzer.jooq.tables.records.JMethodRecord;
import com.example.codeusageanalyzer.jooq.tables.records.JModuleRecord;
import com.example.codeusageanalyzer.jooq.tables.records.JRepositoryRecord;

/**
 * A class modelling foreign key relationships between tables of the
 * <code>PUBLIC</code> schema
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JCalleeRecord, Long> IDENTITY_CALLEE = Identities0.IDENTITY_CALLEE;

    public static final Identity<JClassRecord, Long> IDENTITY_CLASS = Identities0.IDENTITY_CLASS;

    public static final Identity<JDependencyRecord, Long> IDENTITY_DEPENDENCY = Identities0.IDENTITY_DEPENDENCY;

    public static final Identity<JInterfaceRecord, Long> IDENTITY_INTERFACE = Identities0.IDENTITY_INTERFACE;

    public static final Identity<JMethodRecord, Long> IDENTITY_METHOD = Identities0.IDENTITY_METHOD;

    public static final Identity<JModuleRecord, Long> IDENTITY_MODULE = Identities0.IDENTITY_MODULE;

    public static final Identity<JRepositoryRecord, Long> IDENTITY_REPOSITORY = Identities0.IDENTITY_REPOSITORY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JCalleeRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;

    public static final UniqueKey<JClassRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;

    public static final UniqueKey<JDependencyRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;

    public static final UniqueKey<JInterfaceRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;

    public static final UniqueKey<JMethodRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

    public static final UniqueKey<JModuleRecord> CONSTRAINT_87 = UniqueKeys0.CONSTRAINT_87;

    public static final UniqueKey<JRepositoryRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {

        public static Identity<JCalleeRecord, Long> IDENTITY_CALLEE = createIdentity(JCallee.CALLEE,
                JCallee.CALLEE.CALLEE_ID);

        public static Identity<JClassRecord, Long> IDENTITY_CLASS = createIdentity(JClass.CLASS, JClass.CLASS.CLASS_ID);

        public static Identity<JDependencyRecord, Long> IDENTITY_DEPENDENCY = createIdentity(JDependency.DEPENDENCY,
                JDependency.DEPENDENCY.DEPENDENCY_ID);

        public static Identity<JInterfaceRecord, Long> IDENTITY_INTERFACE = createIdentity(JInterface.INTERFACE,
                JInterface.INTERFACE.INTERFACE_ID);

        public static Identity<JMethodRecord, Long> IDENTITY_METHOD = createIdentity(JMethod.METHOD,
                JMethod.METHOD.METHOD_ID);

        public static Identity<JModuleRecord, Long> IDENTITY_MODULE = createIdentity(JModule.MODULE,
                JModule.MODULE.MODULE_ID);

        public static Identity<JRepositoryRecord, Long> IDENTITY_REPOSITORY = createIdentity(JRepository.REPOSITORY,
                JRepository.REPOSITORY.REPOSITORY_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {

        public static final UniqueKey<JCalleeRecord> CONSTRAINT_7 = createUniqueKey(JCallee.CALLEE, "CONSTRAINT_7",
                JCallee.CALLEE.CALLEE_ID);

        public static final UniqueKey<JClassRecord> CONSTRAINT_3 = createUniqueKey(JClass.CLASS, "CONSTRAINT_3",
                JClass.CLASS.CLASS_ID);

        public static final UniqueKey<JDependencyRecord> CONSTRAINT_1 = createUniqueKey(JDependency.DEPENDENCY,
                "CONSTRAINT_1", JDependency.DEPENDENCY.DEPENDENCY_ID);

        public static final UniqueKey<JInterfaceRecord> CONSTRAINT_C = createUniqueKey(JInterface.INTERFACE,
                "CONSTRAINT_C", JInterface.INTERFACE.INTERFACE_ID);

        public static final UniqueKey<JMethodRecord> CONSTRAINT_8 = createUniqueKey(JMethod.METHOD, "CONSTRAINT_8",
                JMethod.METHOD.METHOD_ID);

        public static final UniqueKey<JModuleRecord> CONSTRAINT_87 = createUniqueKey(JModule.MODULE, "CONSTRAINT_87",
                JModule.MODULE.MODULE_ID);

        public static final UniqueKey<JRepositoryRecord> CONSTRAINT_9 = createUniqueKey(JRepository.REPOSITORY,
                "CONSTRAINT_9", JRepository.REPOSITORY.REPOSITORY_ID);
    }
}
