/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence
     * <code>PUBLIC.SYSTEM_SEQUENCE_329F1A32_FD9C_4A30_9AD8_B932786E96B3</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_329F1A32_FD9C_4A30_9AD8_B932786E96B3 = new SequenceImpl<Long>(
            "SYSTEM_SEQUENCE_329F1A32_FD9C_4A30_9AD8_B932786E96B3", JPublic.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence
     * <code>PUBLIC.SYSTEM_SEQUENCE_7344AA6C_A669_4CF1_B5B1_1D444518C7FD</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_7344AA6C_A669_4CF1_B5B1_1D444518C7FD = new SequenceImpl<Long>(
            "SYSTEM_SEQUENCE_7344AA6C_A669_4CF1_B5B1_1D444518C7FD", JPublic.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence
     * <code>PUBLIC.SYSTEM_SEQUENCE_7E7C649D_E9A0_49A3_9F00_1C62CA820F2E</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_7E7C649D_E9A0_49A3_9F00_1C62CA820F2E = new SequenceImpl<Long>(
            "SYSTEM_SEQUENCE_7E7C649D_E9A0_49A3_9F00_1C62CA820F2E", JPublic.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence
     * <code>PUBLIC.SYSTEM_SEQUENCE_847C61D6_2411_425A_BE5F_7696CB151706</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_847C61D6_2411_425A_BE5F_7696CB151706 = new SequenceImpl<Long>(
            "SYSTEM_SEQUENCE_847C61D6_2411_425A_BE5F_7696CB151706", JPublic.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence
     * <code>PUBLIC.SYSTEM_SEQUENCE_B1E2D4A2_0A0C_4447_AF80_82B9EF5D5FDC</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_B1E2D4A2_0A0C_4447_AF80_82B9EF5D5FDC = new SequenceImpl<Long>(
            "SYSTEM_SEQUENCE_B1E2D4A2_0A0C_4447_AF80_82B9EF5D5FDC", JPublic.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence
     * <code>PUBLIC.SYSTEM_SEQUENCE_CDD9F9E2_D1E4_49AD_B1A2_DB99C16DC788</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_CDD9F9E2_D1E4_49AD_B1A2_DB99C16DC788 = new SequenceImpl<Long>(
            "SYSTEM_SEQUENCE_CDD9F9E2_D1E4_49AD_B1A2_DB99C16DC788", JPublic.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence
     * <code>PUBLIC.SYSTEM_SEQUENCE_ED82774E_9477_4D87_9219_588259F46C85</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_ED82774E_9477_4D87_9219_588259F46C85 = new SequenceImpl<Long>(
            "SYSTEM_SEQUENCE_ED82774E_9477_4D87_9219_588259F46C85", JPublic.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
