/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq;

import javax.annotation.Generated;

import com.example.codeusageanalyzer.jooq.tables.JCallee;
import com.example.codeusageanalyzer.jooq.tables.JClass;
import com.example.codeusageanalyzer.jooq.tables.JDependency;
import com.example.codeusageanalyzer.jooq.tables.JInterface;
import com.example.codeusageanalyzer.jooq.tables.JMethod;
import com.example.codeusageanalyzer.jooq.tables.JModule;
import com.example.codeusageanalyzer.jooq.tables.JRepository;

/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CALLEE</code>.
     */
    public static final JCallee CALLEE = com.example.codeusageanalyzer.jooq.tables.JCallee.CALLEE;

    /**
     * The table <code>PUBLIC.CLASS</code>.
     */
    public static final JClass CLASS = com.example.codeusageanalyzer.jooq.tables.JClass.CLASS;

    /**
     * The table <code>PUBLIC.DEPENDENCY</code>.
     */
    public static final JDependency DEPENDENCY = com.example.codeusageanalyzer.jooq.tables.JDependency.DEPENDENCY;

    /**
     * The table <code>PUBLIC.INTERFACE</code>.
     */
    public static final JInterface INTERFACE = com.example.codeusageanalyzer.jooq.tables.JInterface.INTERFACE;

    /**
     * The table <code>PUBLIC.METHOD</code>.
     */
    public static final JMethod METHOD = com.example.codeusageanalyzer.jooq.tables.JMethod.METHOD;

    /**
     * The table <code>PUBLIC.MODULE</code>.
     */
    public static final JModule MODULE = com.example.codeusageanalyzer.jooq.tables.JModule.MODULE;

    /**
     * The table <code>PUBLIC.REPOSITORY</code>.
     */
    public static final JRepository REPOSITORY = com.example.codeusageanalyzer.jooq.tables.JRepository.REPOSITORY;
}
