/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import com.example.codeusageanalyzer.jooq.tables.JCallee;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCalleeRecord extends UpdatableRecordImpl<JCalleeRecord>
        implements Record6<Long, String, Long, String, String, Boolean> {

    private static final long serialVersionUID = 1920157467;

    /**
     * Setter for <code>PUBLIC.CALLEE.CALLEE_ID</code>.
     */
    public void setCalleeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CALLEE.CALLEE_ID</code>.
     */
    public Long getCalleeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CALLEE.DESCRIPTOR</code>.
     */
    public void setDescriptor(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CALLEE.DESCRIPTOR</code>.
     */
    public String getDescriptor() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CALLEE.METHOD_ID</code>.
     */
    public void setMethodId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CALLEE.METHOD_ID</code>.
     */
    public Long getMethodId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CALLEE.METHOD_NAME</code>.
     */
    public void setMethodName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CALLEE.METHOD_NAME</code>.
     */
    public String getMethodName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CALLEE.OWNER_NAME</code>.
     */
    public void setOwnerName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CALLEE.OWNER_NAME</code>.
     */
    public String getOwnerName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CALLEE.INVOKE_DYNAMIC</code>.
     */
    public void setInvokeDynamic(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CALLEE.INVOKE_DYNAMIC</code>.
     */
    public Boolean getInvokeDynamic() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, String, String, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, String, String, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JCallee.CALLEE.CALLEE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JCallee.CALLEE.DESCRIPTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return JCallee.CALLEE.METHOD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JCallee.CALLEE.METHOD_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JCallee.CALLEE.OWNER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return JCallee.CALLEE.INVOKE_DYNAMIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCalleeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescriptor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMethodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMethodName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOwnerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getInvokeDynamic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCalleeRecord value1(Long value) {
        setCalleeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCalleeRecord value2(String value) {
        setDescriptor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCalleeRecord value3(Long value) {
        setMethodId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCalleeRecord value4(String value) {
        setMethodName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCalleeRecord value5(String value) {
        setOwnerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCalleeRecord value6(Boolean value) {
        setInvokeDynamic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCalleeRecord values(Long value1, String value2, Long value3, String value4, String value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JCalleeRecord
     */
    public JCalleeRecord() {
        super(JCallee.CALLEE);
    }

    /**
     * Create a detached, initialised JCalleeRecord
     */
    public JCalleeRecord(Long calleeId, String descriptor, Long methodId, String methodName, String ownerName,
            Boolean invokeDynamic) {
        super(JCallee.CALLEE);

        set(0, calleeId);
        set(1, descriptor);
        set(2, methodId);
        set(3, methodName);
        set(4, ownerName);
        set(5, invokeDynamic);
    }
}
