/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import com.example.codeusageanalyzer.jooq.tables.JDependency;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDependencyRecord extends UpdatableRecordImpl<JDependencyRecord>
        implements Record5<Long, String, String, Long, String> {

    private static final long serialVersionUID = -1674823477;

    /**
     * Setter for <code>PUBLIC.DEPENDENCY.DEPENDENCY_ID</code>.
     */
    public void setDependencyId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.DEPENDENCY.DEPENDENCY_ID</code>.
     */
    public Long getDependencyId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DEPENDENCY.ARTIFACT_ID</code>.
     */
    public void setArtifactId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.DEPENDENCY.ARTIFACT_ID</code>.
     */
    public String getArtifactId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DEPENDENCY.GROUP_ID</code>.
     */
    public void setGroupId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.DEPENDENCY.GROUP_ID</code>.
     */
    public String getGroupId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.DEPENDENCY.MODULE_ID</code>.
     */
    public void setModuleId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.DEPENDENCY.MODULE_ID</code>.
     */
    public Long getModuleId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>PUBLIC.DEPENDENCY.VERSION</code>.
     */
    public void setVersion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.DEPENDENCY.VERSION</code>.
     */
    public String getVersion() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Long, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Long, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JDependency.DEPENDENCY.DEPENDENCY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JDependency.DEPENDENCY.ARTIFACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JDependency.DEPENDENCY.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return JDependency.DEPENDENCY.MODULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JDependency.DEPENDENCY.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getDependencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getArtifactId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDependencyRecord value1(Long value) {
        setDependencyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDependencyRecord value2(String value) {
        setArtifactId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDependencyRecord value3(String value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDependencyRecord value4(Long value) {
        setModuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDependencyRecord value5(String value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JDependencyRecord values(Long value1, String value2, String value3, Long value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDependencyRecord
     */
    public JDependencyRecord() {
        super(JDependency.DEPENDENCY);
    }

    /**
     * Create a detached, initialised JDependencyRecord
     */
    public JDependencyRecord(Long dependencyId, String artifactId, String groupId, Long moduleId, String version) {
        super(JDependency.DEPENDENCY);

        set(0, dependencyId);
        set(1, artifactId);
        set(2, groupId);
        set(3, moduleId);
        set(4, version);
    }
}
