/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import com.example.codeusageanalyzer.jooq.tables.JMethod;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JMethodRecord extends UpdatableRecordImpl<JMethodRecord> implements Record4<Long, Long, String, String> {

    private static final long serialVersionUID = 1305700182;

    /**
     * Setter for <code>PUBLIC.METHOD.METHOD_ID</code>.
     */
    public void setMethodId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.METHOD.METHOD_ID</code>.
     */
    public Long getMethodId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.METHOD.CLASS_ID</code>.
     */
    public void setClassId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.METHOD.CLASS_ID</code>.
     */
    public Long getClassId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.METHOD.DESCRIPTOR</code>.
     */
    public void setDescriptor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.METHOD.DESCRIPTOR</code>.
     */
    public String getDescriptor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.METHOD.METHOD_NAME</code>.
     */
    public void setMethodName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.METHOD.METHOD_NAME</code>.
     */
    public String getMethodName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JMethod.METHOD.METHOD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return JMethod.METHOD.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JMethod.METHOD.DESCRIPTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JMethod.METHOD.METHOD_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getMethodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescriptor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMethodName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JMethodRecord value1(Long value) {
        setMethodId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JMethodRecord value2(Long value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JMethodRecord value3(String value) {
        setDescriptor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JMethodRecord value4(String value) {
        setMethodName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JMethodRecord values(Long value1, Long value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JMethodRecord
     */
    public JMethodRecord() {
        super(JMethod.METHOD);
    }

    /**
     * Create a detached, initialised JMethodRecord
     */
    public JMethodRecord(Long methodId, Long classId, String descriptor, String methodName) {
        super(JMethod.METHOD);

        set(0, methodId);
        set(1, classId);
        set(2, descriptor);
        set(3, methodName);
    }
}
