/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import com.example.codeusageanalyzer.jooq.tables.JModule;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JModuleRecord extends UpdatableRecordImpl<JModuleRecord>
        implements Record6<Long, String, String, String, Long, String> {

    private static final long serialVersionUID = -170062420;

    /**
     * Setter for <code>PUBLIC.MODULE.MODULE_ID</code>.
     */
    public void setModuleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.MODULE.MODULE_ID</code>.
     */
    public Long getModuleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.MODULE.ARTIFACT_ID</code>.
     */
    public void setArtifactId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.MODULE.ARTIFACT_ID</code>.
     */
    public String getArtifactId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.MODULE.GROUP_ID</code>.
     */
    public void setGroupId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.MODULE.GROUP_ID</code>.
     */
    public String getGroupId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.MODULE.PATH</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.MODULE.PATH</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.MODULE.REPOSITORY_ID</code>.
     */
    public void setRepositoryId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.MODULE.REPOSITORY_ID</code>.
     */
    public Long getRepositoryId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>PUBLIC.MODULE.VERSION</code>.
     */
    public void setVersion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.MODULE.VERSION</code>.
     */
    public String getVersion() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JModule.MODULE.MODULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JModule.MODULE.ARTIFACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JModule.MODULE.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JModule.MODULE.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return JModule.MODULE.REPOSITORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return JModule.MODULE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getArtifactId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getRepositoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModuleRecord value1(Long value) {
        setModuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModuleRecord value2(String value) {
        setArtifactId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModuleRecord value3(String value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModuleRecord value4(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModuleRecord value5(Long value) {
        setRepositoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModuleRecord value6(String value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JModuleRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JModuleRecord
     */
    public JModuleRecord() {
        super(JModule.MODULE);
    }

    /**
     * Create a detached, initialised JModuleRecord
     */
    public JModuleRecord(Long moduleId, String artifactId, String groupId, String path, Long repositoryId,
            String version) {
        super(JModule.MODULE);

        set(0, moduleId);
        set(1, artifactId);
        set(2, groupId);
        set(3, path);
        set(4, repositoryId);
        set(5, version);
    }
}
