/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.records;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import com.example.codeusageanalyzer.jooq.tables.JRepository;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRepositoryRecord extends UpdatableRecordImpl<JRepositoryRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -998430624;

    /**
     * Setter for <code>PUBLIC.REPOSITORY.REPOSITORY_ID</code>.
     */
    public void setRepositoryId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.REPOSITORY.REPOSITORY_ID</code>.
     */
    public Long getRepositoryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.REPOSITORY.URL</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.REPOSITORY.URL</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JRepository.REPOSITORY.REPOSITORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JRepository.REPOSITORY.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getRepositoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JRepositoryRecord value1(Long value) {
        setRepositoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JRepositoryRecord value2(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JRepositoryRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JRepositoryRecord
     */
    public JRepositoryRecord() {
        super(JRepository.REPOSITORY);
    }

    /**
     * Create a detached, initialised JRepositoryRecord
     */
    public JRepositoryRecord(Long repositoryId, String url) {
        super(JRepository.REPOSITORY);

        set(0, repositoryId);
        set(1, url);
    }
}
