/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.daos;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import com.example.codeusageanalyzer.jooq.tables.JDependency;
import com.example.codeusageanalyzer.jooq.tables.pojos.JDependencyPojo;
import com.example.codeusageanalyzer.jooq.tables.records.JDependencyRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDependencyDao extends DAOImpl<JDependencyRecord, JDependencyPojo, Long> {

    /**
     * Create a new JDependencyDao without any configuration
     */
    public JDependencyDao() {
        super(JDependency.DEPENDENCY, JDependencyPojo.class);
    }

    /**
     * Create a new JDependencyDao with an attached configuration
     */
    public JDependencyDao(Configuration configuration) {
        super(JDependency.DEPENDENCY, JDependencyPojo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(JDependencyPojo object) {
        return object.getDependencyId();
    }

    /**
     * Fetch records that have <code>DEPENDENCY_ID IN (values)</code>
     */
    public List<JDependencyPojo> fetchByJDependencyId(Long... values) {
        return fetch(JDependency.DEPENDENCY.DEPENDENCY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>DEPENDENCY_ID = value</code>
     */
    public JDependencyPojo fetchOneByJDependencyId(Long value) {
        return fetchOne(JDependency.DEPENDENCY.DEPENDENCY_ID, value);
    }

    /**
     * Fetch records that have <code>ARTIFACT_ID IN (values)</code>
     */
    public List<JDependencyPojo> fetchByJArtifactId(String... values) {
        return fetch(JDependency.DEPENDENCY.ARTIFACT_ID, values);
    }

    /**
     * Fetch records that have <code>GROUP_ID IN (values)</code>
     */
    public List<JDependencyPojo> fetchByJGroupId(String... values) {
        return fetch(JDependency.DEPENDENCY.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>MODULE_ID IN (values)</code>
     */
    public List<JDependencyPojo> fetchByJModuleId(Long... values) {
        return fetch(JDependency.DEPENDENCY.MODULE_ID, values);
    }

    /**
     * Fetch records that have <code>VERSION IN (values)</code>
     */
    public List<JDependencyPojo> fetchByJVersion(String... values) {
        return fetch(JDependency.DEPENDENCY.VERSION, values);
    }
}
