/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.daos;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import com.example.codeusageanalyzer.jooq.tables.JInterface;
import com.example.codeusageanalyzer.jooq.tables.pojos.JInterfacePojo;
import com.example.codeusageanalyzer.jooq.tables.records.JInterfaceRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JInterfaceDao extends DAOImpl<JInterfaceRecord, JInterfacePojo, Long> {

    /**
     * Create a new JInterfaceDao without any configuration
     */
    public JInterfaceDao() {
        super(JInterface.INTERFACE, JInterfacePojo.class);
    }

    /**
     * Create a new JInterfaceDao with an attached configuration
     */
    public JInterfaceDao(Configuration configuration) {
        super(JInterface.INTERFACE, JInterfacePojo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(JInterfacePojo object) {
        return object.getInterfaceId();
    }

    /**
     * Fetch records that have <code>INTERFACE_ID IN (values)</code>
     */
    public List<JInterfacePojo> fetchByJInterfaceId(Long... values) {
        return fetch(JInterface.INTERFACE.INTERFACE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>INTERFACE_ID = value</code>
     */
    public JInterfacePojo fetchOneByJInterfaceId(Long value) {
        return fetchOne(JInterface.INTERFACE.INTERFACE_ID, value);
    }

    /**
     * Fetch records that have <code>CLASS_ID IN (values)</code>
     */
    public List<JInterfacePojo> fetchByJClassId(Long... values) {
        return fetch(JInterface.INTERFACE.CLASS_ID, values);
    }

    /**
     * Fetch records that have <code>INTERFACE_NAME IN (values)</code>
     */
    public List<JInterfacePojo> fetchByJInterfaceName(String... values) {
        return fetch(JInterface.INTERFACE.INTERFACE_NAME, values);
    }
}
