/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.daos;


import com.example.codeusageanalyzer.jooq.tables.JModule;
import com.example.codeusageanalyzer.jooq.tables.pojos.JModulePojo;
import com.example.codeusageanalyzer.jooq.tables.records.JModuleRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JModuleDao extends DAOImpl<JModuleRecord, JModulePojo, String> {

    /**
     * Create a new JModuleDao without any configuration
     */
    public JModuleDao() {
        super(JModule.MODULE, JModulePojo.class);
    }

    /**
     * Create a new JModuleDao with an attached configuration
     */
    public JModuleDao(Configuration configuration) {
        super(JModule.MODULE, JModulePojo.class, configuration);
    }

    @Override
    public String getId(JModulePojo object) {
        return object.getModuleId();
    }

    /**
     * Fetch records that have <code>MODULE_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JModulePojo> fetchRangeOfJModuleId(String lowerInclusive, String upperInclusive) {
        return fetchRange(JModule.MODULE.MODULE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODULE_ID IN (values)</code>
     */
    public List<JModulePojo> fetchByJModuleId(String... values) {
        return fetch(JModule.MODULE.MODULE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>MODULE_ID = value</code>
     */
    public JModulePojo fetchOneByJModuleId(String value) {
        return fetchOne(JModule.MODULE.MODULE_ID, value);
    }

    /**
     * Fetch records that have <code>ARTIFACT_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JModulePojo> fetchRangeOfJArtifactId(String lowerInclusive, String upperInclusive) {
        return fetchRange(JModule.MODULE.ARTIFACT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ARTIFACT_ID IN (values)</code>
     */
    public List<JModulePojo> fetchByJArtifactId(String... values) {
        return fetch(JModule.MODULE.ARTIFACT_ID, values);
    }

    /**
     * Fetch records that have <code>GROUP_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JModulePojo> fetchRangeOfJGroupId(String lowerInclusive, String upperInclusive) {
        return fetchRange(JModule.MODULE.GROUP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>GROUP_ID IN (values)</code>
     */
    public List<JModulePojo> fetchByJGroupId(String... values) {
        return fetch(JModule.MODULE.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>PATH BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JModulePojo> fetchRangeOfJPath(String lowerInclusive, String upperInclusive) {
        return fetchRange(JModule.MODULE.PATH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PATH IN (values)</code>
     */
    public List<JModulePojo> fetchByJPath(String... values) {
        return fetch(JModule.MODULE.PATH, values);
    }

    /**
     * Fetch records that have <code>REPOSITORY_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JModulePojo> fetchRangeOfJRepositoryId(String lowerInclusive, String upperInclusive) {
        return fetchRange(JModule.MODULE.REPOSITORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>REPOSITORY_ID IN (values)</code>
     */
    public List<JModulePojo> fetchByJRepositoryId(String... values) {
        return fetch(JModule.MODULE.REPOSITORY_ID, values);
    }

    /**
     * Fetch records that have <code>VERSION BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JModulePojo> fetchRangeOfJVersion(String lowerInclusive, String upperInclusive) {
        return fetchRange(JModule.MODULE.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>VERSION IN (values)</code>
     */
    public List<JModulePojo> fetchByJVersion(String... values) {
        return fetch(JModule.MODULE.VERSION, values);
    }
}
