/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.daos;


import com.example.codeusageanalyzer.jooq.tables.JRepository;
import com.example.codeusageanalyzer.jooq.tables.pojos.JRepositoryPojo;
import com.example.codeusageanalyzer.jooq.tables.records.JRepositoryRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRepositoryDao extends DAOImpl<JRepositoryRecord, JRepositoryPojo, String> {

    /**
     * Create a new JRepositoryDao without any configuration
     */
    public JRepositoryDao() {
        super(JRepository.REPOSITORY, JRepositoryPojo.class);
    }

    /**
     * Create a new JRepositoryDao with an attached configuration
     */
    public JRepositoryDao(Configuration configuration) {
        super(JRepository.REPOSITORY, JRepositoryPojo.class, configuration);
    }

    @Override
    public String getId(JRepositoryPojo object) {
        return object.getRepositoryId();
    }

    /**
     * Fetch records that have <code>REPOSITORY_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JRepositoryPojo> fetchRangeOfJRepositoryId(String lowerInclusive, String upperInclusive) {
        return fetchRange(JRepository.REPOSITORY.REPOSITORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>REPOSITORY_ID IN (values)</code>
     */
    public List<JRepositoryPojo> fetchByJRepositoryId(String... values) {
        return fetch(JRepository.REPOSITORY.REPOSITORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>REPOSITORY_ID = value</code>
     */
    public JRepositoryPojo fetchOneByJRepositoryId(String value) {
        return fetchOne(JRepository.REPOSITORY.REPOSITORY_ID, value);
    }

    /**
     * Fetch records that have <code>URL BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<JRepositoryPojo> fetchRangeOfJUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(JRepository.REPOSITORY.URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>URL IN (values)</code>
     */
    public List<JRepositoryPojo> fetchByJUrl(String... values) {
        return fetch(JRepository.REPOSITORY.URL, values);
    }
}
