/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables;


import com.example.codeusageanalyzer.jooq.DefaultSchema;
import com.example.codeusageanalyzer.jooq.Keys;
import com.example.codeusageanalyzer.jooq.tables.records.JInterfaceRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JInterface extends TableImpl<JInterfaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>INTERFACE</code>
     */
    public static final JInterface INTERFACE = new JInterface();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JInterfaceRecord> getRecordType() {
        return JInterfaceRecord.class;
    }

    /**
     * The column <code>INTERFACE.INTERFACE_ID</code>.
     */
    public final TableField<JInterfaceRecord, String> INTERFACE_ID = createField(DSL.name("INTERFACE_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>INTERFACE.CLASS_ID</code>.
     */
    public final TableField<JInterfaceRecord, String> CLASS_ID = createField(DSL.name("CLASS_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>INTERFACE.INTERFACE_NAME</code>.
     */
    public final TableField<JInterfaceRecord, String> INTERFACE_NAME = createField(DSL.name("INTERFACE_NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private JInterface(Name alias, Table<JInterfaceRecord> aliased) {
        this(alias, aliased, null);
    }

    private JInterface(Name alias, Table<JInterfaceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>INTERFACE</code> table reference
     */
    public JInterface(String alias) {
        this(DSL.name(alias), INTERFACE);
    }

    /**
     * Create an aliased <code>INTERFACE</code> table reference
     */
    public JInterface(Name alias) {
        this(alias, INTERFACE);
    }

    /**
     * Create a <code>INTERFACE</code> table reference
     */
    public JInterface() {
        this(DSL.name("INTERFACE"), null);
    }

    public <O extends Record> JInterface(Table<O> child, ForeignKey<O, JInterfaceRecord> key) {
        super(child, key, INTERFACE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<JInterfaceRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    public List<UniqueKey<JInterfaceRecord>> getKeys() {
        return Arrays.<UniqueKey<JInterfaceRecord>>asList(Keys.CONSTRAINT_C);
    }

    @Override
    public JInterface as(String alias) {
        return new JInterface(DSL.name(alias), this);
    }

    @Override
    public JInterface as(Name alias) {
        return new JInterface(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JInterface rename(String name) {
        return new JInterface(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JInterface rename(Name name) {
        return new JInterface(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
