/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables;


import com.example.codeusageanalyzer.jooq.DefaultSchema;
import com.example.codeusageanalyzer.jooq.Keys;
import com.example.codeusageanalyzer.jooq.tables.records.JMethodRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JMethod extends TableImpl<JMethodRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>METHOD</code>
     */
    public static final JMethod METHOD = new JMethod();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JMethodRecord> getRecordType() {
        return JMethodRecord.class;
    }

    /**
     * The column <code>METHOD.METHOD_ID</code>.
     */
    public final TableField<JMethodRecord, String> METHOD_ID = createField(DSL.name("METHOD_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>METHOD.CLASS_ID</code>.
     */
    public final TableField<JMethodRecord, String> CLASS_ID = createField(DSL.name("CLASS_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>METHOD.DESCRIPTOR</code>.
     */
    public final TableField<JMethodRecord, String> DESCRIPTOR = createField(DSL.name("DESCRIPTOR"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>METHOD.METHOD_NAME</code>.
     */
    public final TableField<JMethodRecord, String> METHOD_NAME = createField(DSL.name("METHOD_NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private JMethod(Name alias, Table<JMethodRecord> aliased) {
        this(alias, aliased, null);
    }

    private JMethod(Name alias, Table<JMethodRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>METHOD</code> table reference
     */
    public JMethod(String alias) {
        this(DSL.name(alias), METHOD);
    }

    /**
     * Create an aliased <code>METHOD</code> table reference
     */
    public JMethod(Name alias) {
        this(alias, METHOD);
    }

    /**
     * Create a <code>METHOD</code> table reference
     */
    public JMethod() {
        this(DSL.name("METHOD"), null);
    }

    public <O extends Record> JMethod(Table<O> child, ForeignKey<O, JMethodRecord> key) {
        super(child, key, METHOD);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<JMethodRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    public List<UniqueKey<JMethodRecord>> getKeys() {
        return Arrays.<UniqueKey<JMethodRecord>>asList(Keys.CONSTRAINT_8);
    }

    @Override
    public JMethod as(String alias) {
        return new JMethod(DSL.name(alias), this);
    }

    @Override
    public JMethod as(Name alias) {
        return new JMethod(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JMethod rename(String name) {
        return new JMethod(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JMethod rename(Name name) {
        return new JMethod(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
