/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;

import java.io.Serializable;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCalleePojo implements Serializable {

    private static final long serialVersionUID = 253450340;

    private Long calleeId;

    private String descriptor;

    private Boolean invokeDynamic;

    private Long methodId;

    private String methodName;

    private String ownerName;

    public JCalleePojo() {
    }

    public JCalleePojo(JCalleePojo value) {
        this.calleeId = value.calleeId;
        this.descriptor = value.descriptor;
        this.invokeDynamic = value.invokeDynamic;
        this.methodId = value.methodId;
        this.methodName = value.methodName;
        this.ownerName = value.ownerName;
    }

    public JCalleePojo(Long calleeId, String descriptor, Boolean invokeDynamic, Long methodId, String methodName,
            String ownerName) {
        this.calleeId = calleeId;
        this.descriptor = descriptor;
        this.invokeDynamic = invokeDynamic;
        this.methodId = methodId;
        this.methodName = methodName;
        this.ownerName = ownerName;
    }

    public Long getCalleeId() {
        return this.calleeId;
    }

    public void setCalleeId(Long calleeId) {
        this.calleeId = calleeId;
    }

    public String getDescriptor() {
        return this.descriptor;
    }

    public void setDescriptor(String descriptor) {
        this.descriptor = descriptor;
    }

    public Boolean getInvokeDynamic() {
        return this.invokeDynamic;
    }

    public void setInvokeDynamic(Boolean invokeDynamic) {
        this.invokeDynamic = invokeDynamic;
    }

    public Long getMethodId() {
        return this.methodId;
    }

    public void setMethodId(Long methodId) {
        this.methodId = methodId;
    }

    public String getMethodName() {
        return this.methodName;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public String getOwnerName() {
        return this.ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JCalleePojo (");

        sb.append(calleeId);
        sb.append(", ").append(descriptor);
        sb.append(", ").append(invokeDynamic);
        sb.append(", ").append(methodId);
        sb.append(", ").append(methodName);
        sb.append(", ").append(ownerName);

        sb.append(")");
        return sb.toString();
    }
}
