/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;

import java.io.Serializable;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassPojo implements Serializable {

    private static final long serialVersionUID = -51716719;

    private Long classId;

    private String className;

    private Long moduleId;

    private String superClassName;

    private String path;

    public JClassPojo() {
    }

    public JClassPojo(JClassPojo value) {
        this.classId = value.classId;
        this.className = value.className;
        this.moduleId = value.moduleId;
        this.superClassName = value.superClassName;
        this.path = value.path;
    }

    public JClassPojo(Long classId, String className, Long moduleId, String superClassName, String path) {
        this.classId = classId;
        this.className = className;
        this.moduleId = moduleId;
        this.superClassName = superClassName;
        this.path = path;
    }

    public Long getClassId() {
        return this.classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Long getModuleId() {
        return this.moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public String getSuperClassName() {
        return this.superClassName;
    }

    public void setSuperClassName(String superClassName) {
        this.superClassName = superClassName;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JClassPojo (");

        sb.append(classId);
        sb.append(", ").append(className);
        sb.append(", ").append(moduleId);
        sb.append(", ").append(superClassName);
        sb.append(", ").append(path);

        sb.append(")");
        return sb.toString();
    }
}
