/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;

import java.io.Serializable;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JDependencyPojo implements Serializable {

    private static final long serialVersionUID = -212400813;

    private Long dependencyId;

    private String artifactId;

    private String groupId;

    private Long moduleId;

    private String version;

    public JDependencyPojo() {
    }

    public JDependencyPojo(JDependencyPojo value) {
        this.dependencyId = value.dependencyId;
        this.artifactId = value.artifactId;
        this.groupId = value.groupId;
        this.moduleId = value.moduleId;
        this.version = value.version;
    }

    public JDependencyPojo(Long dependencyId, String artifactId, String groupId, Long moduleId, String version) {
        this.dependencyId = dependencyId;
        this.artifactId = artifactId;
        this.groupId = groupId;
        this.moduleId = moduleId;
        this.version = version;
    }

    public Long getDependencyId() {
        return this.dependencyId;
    }

    public void setDependencyId(Long dependencyId) {
        this.dependencyId = dependencyId;
    }

    public String getArtifactId() {
        return this.artifactId;
    }

    public void setArtifactId(String artifactId) {
        this.artifactId = artifactId;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Long getModuleId() {
        return this.moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JDependencyPojo (");

        sb.append(dependencyId);
        sb.append(", ").append(artifactId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(moduleId);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
