/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;

import java.io.Serializable;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JInterfacePojo implements Serializable {

    private static final long serialVersionUID = 502965334;

    private Long interfaceId;

    private Long classId;

    private String interfaceName;

    public JInterfacePojo() {
    }

    public JInterfacePojo(JInterfacePojo value) {
        this.interfaceId = value.interfaceId;
        this.classId = value.classId;
        this.interfaceName = value.interfaceName;
    }

    public JInterfacePojo(Long interfaceId, Long classId, String interfaceName) {
        this.interfaceId = interfaceId;
        this.classId = classId;
        this.interfaceName = interfaceName;
    }

    public Long getInterfaceId() {
        return this.interfaceId;
    }

    public void setInterfaceId(Long interfaceId) {
        this.interfaceId = interfaceId;
    }

    public Long getClassId() {
        return this.classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public String getInterfaceName() {
        return this.interfaceName;
    }

    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JInterfacePojo (");

        sb.append(interfaceId);
        sb.append(", ").append(classId);
        sb.append(", ").append(interfaceName);

        sb.append(")");
        return sb.toString();
    }
}
