/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq.tables.pojos;

import java.io.Serializable;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRepositoryPojo implements Serializable {

    private static final long serialVersionUID = 1480754753;

    private Long repositoryId;

    private String url;

    public JRepositoryPojo() {
    }

    public JRepositoryPojo(JRepositoryPojo value) {
        this.repositoryId = value.repositoryId;
        this.url = value.url;
    }

    public JRepositoryPojo(Long repositoryId, String url) {
        this.repositoryId = repositoryId;
        this.url = url;
    }

    public Long getRepositoryId() {
        return this.repositoryId;
    }

    public void setRepositoryId(Long repositoryId) {
        this.repositoryId = repositoryId;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JRepositoryPojo (");

        sb.append(repositoryId);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
