/*
 * This file is generated by jOOQ.
 */
package com.example.codeusageanalyzer.jooq;


import com.example.codeusageanalyzer.jooq.tables.JCallee;
import com.example.codeusageanalyzer.jooq.tables.JClass;
import com.example.codeusageanalyzer.jooq.tables.JDependency;
import com.example.codeusageanalyzer.jooq.tables.JInterface;
import com.example.codeusageanalyzer.jooq.tables.JMethod;
import com.example.codeusageanalyzer.jooq.tables.JModule;
import com.example.codeusageanalyzer.jooq.tables.JRepository;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CALLEE</code>.
     */
    public static final JCallee CALLEE = JCallee.CALLEE;

    /**
     * The table <code>CLASS</code>.
     */
    public static final JClass CLASS = JClass.CLASS;

    /**
     * The table <code>DEPENDENCY</code>.
     */
    public static final JDependency DEPENDENCY = JDependency.DEPENDENCY;

    /**
     * The table <code>INTERFACE</code>.
     */
    public static final JInterface INTERFACE = JInterface.INTERFACE;

    /**
     * The table <code>METHOD</code>.
     */
    public static final JMethod METHOD = JMethod.METHOD;

    /**
     * The table <code>MODULE</code>.
     */
    public static final JModule MODULE = JModule.MODULE;

    /**
     * The table <code>REPOSITORY</code>.
     */
    public static final JRepository REPOSITORY = JRepository.REPOSITORY;
}
